# Generated by Django 3.2.7 on 2021-09-04 19:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_owner', models.CharField(max_length=99)),
                ('project_repo', models.CharField(max_length=99)),
                ('pull_request_id', models.IntegerField()),
                ('comment_text', models.CharField(max_length=2000)),
                ('language', models.IntegerField(choices=[('-1', "Programming Language's info unavailable"), ('0', 'Other programming language'), ('1', 'Java'), ('2', 'Python'), ('3', 'JavaScript'), ('4', 'PHP'), ('5', 'TypeScript'), ('6', 'C#'), ('7', 'C++'), ('8', 'C'), ('9', 'GoLang'), ('10', 'Ruby')], default='-1')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=50)),
                ('comment_id', models.CharField(max_length=50)),
                ('commit_hash', models.CharField(max_length=50)),
                ('decision', models.IntegerField(choices=[(0, 'True Positive'), (1, 'False Positive'), (2, 'Possibly True Positive'), (3, 'Possibly False Positive'), (-1, 'Nobody evaluated yet')], default=-1)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.request')),
            ],
        ),
    ]
