# Generated by Django 3.2.7 on 2021-09-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='language',
            field=models.IntegerField(choices=[(-1, "Programming Language's info unavailable"), (0, 'Other programming language'), (1, 'Java'), (2, 'Python'), (3, 'JavaScript'), (4, 'PHP'), (5, 'TypeScript'), (6, 'C#'), (7, 'C++'), (8, 'C'), (9, 'GoLang'), (10, 'Ruby')], default=-1),
        ),
    ]
