# Generated by Django 3.2.9 on 2021-11-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_mergecommit'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='tips',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
